### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by WINGSIGOD** [SonicCloudOrg/sonic-server#467]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

docker最新版本

### Deploy platform

docker

### Minimal reproduce step

ios设备连接时候点击屏幕内内容会报错
`2024-07-31 16:44:21.084 - INFO 48172 --- [http-nio-7777-exec-4] o.c.sonic.agent.websockets.IOSWSServer   : IOSWSServer-00008030-000229D93468802E send: {"detail":"tap","type":"debug","point":"246,512"}
2024-07-31 16:44:21.086 - INFO 48172 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool   : accept 127.0.0.1:11339
[sonic-driver-core] 2024-07-31 16:44:21 [ERROR] perform failed.
org.cloud.sonic.driver.common.tool.SonicRespException: Unhandled endpoint: /session/ACA30649-8E42-4A78-B310-047B120288DC/wda/touch/multi/perform -- http://127.0.0.1:11047/ with parameters {
    wildcards =     (
        "session/ACA30649-8E42-4A78-B310-047B120288DC/wda/touch/multi/perform"
    );
}
        at org.cloud.sonic.driver.ios.service.impl.WdaClientImpl.performTouchAction(WdaClientImpl.java:214)
        at org.cloud.sonic.driver.ios.IOSDriver.performTouchAction(IOSDriver.java:233)
        at org.cloud.sonic.driver.ios.IOSDriver.tap(IOSDriver.java:174)
        at org.cloud.sonic.agent.websockets.IOSWSServer.lambda$onMessage$3(IOSWSServer.java:326)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
用我们的wda
